---
version: "3.9"
networks:
  agoston:
services:
  postgres:
    healthcheck:
      test: "su - postgres -c 'pg_isready -d agoston'"
      interval: 5s
      retries: 5
    image: agoston-postgres-dev
    build:
      context: ./agoston-postgres
    command: >
      -c search_path='agoston_private,agoston_public,agoston_api,agoston_identity,agoston_metadata,public'
      -c timezone='Europe/Zurich'
      -c tcp_keepalives_idle=60
      -c log_min_messages=${PG_LOG_MIN_MESSAGES:-WARNING}
    environment:
      - TC_ENABLED=1
      - TC_DEV=eth0
      - TC_UPLOAD_KBPS=16
      - TC_UPLOAD_CBURST_KB=2048
      - POSTGRES_DB=agoston
      - POSTGRES_PASSWORD=agoston
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.tcp_keepalive_time=60
    volumes:
      - ./tests:/tests
    networks:
      - agoston
    ports:
      - "5552:5432" # Connection developers

  postgraphile:
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: >
        wget -q -O- --no-check-certificate
        --header='Content-Type:application/json'
        --post-data '{"query":"query {session}"}'
        https://localhost:8043/data/graphql
        || exit 1
      interval: 5s
      retries: 5
    image: agoston-postgraphile-dev
    build:
      context: .
    environment:
      - TC_ENABLED=1
      - TC_DEV=eth0
      - TC_UPLOAD_KBPS=16
      - TC_UPLOAD_CBURST_KB=2048
      - PG_POOL_MAX_SIZE=2
      - ENVIRONMENT_NAME=development
      - LOG_LEVEL=silly
      - HTTPS_LISTENING=true
      - HTTPS_PORT_CERTIFICATE=/ssl/graphile.agoston.dev.local.crt
      - HTTPS_PORT_PRIVATEKEY=/ssl/graphile.agoston.dev.local.key
      - HTTP_BACKEND_ORIGIN=https://graphile.agoston.dev.local:8043
      - NODE_ENV=development
      - AUTH_STRATEGIES={"http-bearer":{"enable":true},"user-pwd":{"enable":true,"params":{"createUserIfNotExits":true,"usernameComplexityPattern":"^user-[0-9]*$","passwordComplexityPattern":"^[a-z]*$"}}}
      - CORS_ORIGIN=http://localhost:3000,https://localhost:3000,http://127.0.0.1:3000,https://127.0.0.1:3000,http://graphile.agoston.dev.local:8080,https://graphile.agoston.dev.local:8043
      - UPLOAD_DIR_NAME=/uploads
      - AUTH_OIDC=[${AUTH0_DEV}]
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.tcp_keepalive_time=60
    volumes:
      - ./tests:/tests
      - ./src:/app
      - ./dev/ssl:/ssl
      - /tmp:/uploads
    working_dir: /app
    networks:
      - agoston
    ports:
      - "8080:8080" # Connection app HTTP
      - "8043:8043" # Connection app HTTPS
