---
version: "3.9"
networks:
  agoston:
services:
  postgres:
    healthcheck:
      test: "su - postgres -c 'pg_isready -d agoston'"
      interval: 5s
      retries: 5
    image: agostops/agoston-postgres:v16.2.0
    pull_policy: always
    command: >
      -c search_path='agoston_public,agoston_api,agoston_identity,agoston_metadata,public'
      -c timezone='Europe/Zurich'
      -c tcp_keepalives_idle=60
    environment:
      - POSTGRES_DB=agoston
      - POSTGRES_PASSWORD=agoston
    sysctls:
      - net.ipv4.tcp_keepalive_time=60
    networks:
      - agoston
    ports:
      - "5552:5432"

  postgraphile:
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: >
        wget -q -O-
        --header='Content-Type:application/json'
        --post-data '{"query":"query {session}"}'
        http://localhost:8080/data/graphql
        | grep anonymous || exit 1
      interval: 5s
      retries: 5
    image: agoston-postgraphile-dev
    build: .
    environment:
      - ENVIRONMENT_NAME=development
      - HTTPS_LISTENING=true
      - HTTPS_PORT_CERTIFICATE=/ssl/graphile.agoston.dev.local.crt
      - HTTPS_PORT_PRIVATEKEY=/ssl/graphile.agoston.dev.local.key
      - HTTP_BACKEND_ORIGIN=https://graphile.agoston.dev.local:8043
      - NODE_ENV=development
      - AUTH_STRATEGIES={"http-bearer":{"enable":true},"user-pwd":{"enable":true}}
      - CORS_ORIGIN=http://localhost:3000,https://localhost:3000,http://127.0.0.1:3000,https://127.0.0.1:3000,http://graphile.agoston.dev.local:8080,https://graphile.agoston.dev.local:8043
      - UPLOAD_DIR_NAME=/uploads
    sysctls:
      - net.ipv4.tcp_keepalive_time=60
    volumes:
      - ./src:/app
      - ./dev/ssl:/ssl
      - /tmp:/uploads
    working_dir: /app
    networks:
      - agoston
    ports:
      - "8080:8080"
      - "8043:8043"
